
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_LOADED = 'SET_LOADED'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const PLUS_ITEM = 'PLUS_ITEM'
export const MINUS_ITEM = 'MINUS_ITEM'
export const SET_INITIAL_STATE_TO_CART = 'SET_INITIAL_STATE_TO_CART'


